# vim:set ft=tmux:

# --> Gruvbox Light
set -ogq @thm_bg "#fbf1c7"
set -ogq @thm_fg "#3c3836"

# Colors
set -ogq @thm_rosewater "#b16286"
set -ogq @thm_flamingo "#cc241d"
set -ogq @thm_rosewater "#b16286"
set -ogq @thm_pink "#b16286"
set -ogq @thm_mauve "#8f3f71"
set -ogq @thm_red "#cc241d"
set -ogq @thm_maroon "#9d0006"
set -ogq @thm_peach "#d65d0e"
set -ogq @thm_yellow "#d79921"
set -ogq @thm_green "#98971a"
set -ogq @thm_teal "#689d6a"
set -ogq @thm_sky "#689d6a"
set -ogq @thm_sapphire "#458588"
set -ogq @thm_blue "#458588"
set -ogq @thm_lavender "#076678"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#282828"
set -ogq @thm_subtext_0 "#3c3836"
set -ogq @thm_overlay_2 "#504945"
set -ogq @thm_overlay_1 "#665c54"
set -ogq @thm_overlay_0 "#7c6f64"
set -ogq @thm_surface_2 "#928374"
set -ogq @thm_surface_1 "#a89984"
set -ogq @thm_surface_0 "#d5c4a1"
set -ogq @thm_mantle "#ebdbb2"
set -ogq @thm_crust "#d5c4a1"
