[general]
import = ["~/.config/alacritty/themes/solarized_light.toml"]

[font]
size = 10.0
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }

# [window]
# opacity = 0.8

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
term = "xterm-256color"
