[general]
import = ["~/.config/alacritty/themes/mocha.toml"]

[font]
size = 10.0
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }

# translucent background so the wallpaper shows through
[window]
opacity = 0.85
blur = true

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
term = "xterm-256color"
